### ISSUE TITLE
Long load times on saved dataset

### ISSUE THREAD

**Issue by Ecskrabacz10** [yt-project/yt#4565] opened 2023-07-05 19:01 UTC
Hello! This is not necessarily a bug report, but a question on how I can improve on saving and loading a dataset.

I have currently been working with a filetype from a simulation not currently supported by yt. I have been able to get a dataset, get a time series, and save a dataset. For some context, I have made my own dataset with ~4.2e6 particles and the following fields:

```
[("all","particle_index")]
[("all","particle_mass")]
[("all","particle_type")]
[("all","particle_position_x")]
[("all","particle_position_y")]
[("all","particle_position_z")]
[("all","particle_velocity_x")]
[("all","particle_velocity_y")]
[("all","particle_velocity_z")]
```
Each of the particle types has the same fields, i.e. `[("stable matter","particle_position_x")]`. I have changed values in the dataset (such as current_time, current_redshift, hubble_constant, etc) as well. Currently, I have been saving these datasets to mitigate a memory issue by the command `ad.save_as_dataset(path, fields = ds.field_list)` , where ds is the dataset and `ad = ds.all_data()` . Naturally, this saves both the .h5 file and the .ewah file.

Now is where I run into an issue. I am able to load the saved file and perform the same command to define ad with no issue. It takes only around one second to load the particle index. However, the software takes around 2.5 minutes to load some of the saved data through, say, `pos_x = ad[("all","particle_position_x")]` . This would normally be a non-issue, but when trying to load every field in the field_list, this could easily take a little under half an hour for each of the particle types. 

Could anyone give me any advice as to how I can make the loading process quicker? Am I possibly saving my dataset incorrectly?

**Comment by chrishavlin** [comment] 2023-07-17 21:14
Hi there! apologies for the slow response. 

I don't think you're doing anything incorrectly, I think you're hitting some performance limits... but I think I might have a fix incoming to speed things up. Just to double check -- how are you initially loading in your data to get your initial yt dataset? using `yt.load_particles`?

**Comment by chrishavlin** [comment] 2023-07-17 22:06
@Ecskrabacz10 I just opened a PR that should speed things up for you when you're loading back in via `all_data()`. Would you be able to check out that PR and see if it works for you? You'd need to install from source off of my branch in that PR (let me know if you need a hand doing that). Also, I think it will only really speed things for `all_data()`, might not help as much for other data selections...

**Comment by neutrinoceros** [comment] 2023-07-18 13:26
> I would love some help for installing the PR from source off of your branch.

Here's how. Note that it'll take longer than regular installation (about a couple minutes), because your computer will run extra compilation steps.
```shell
python -m pip install git+https://github.com/chrishavlin/yt@ytdata_check_for_all_data
```

**Comment by chrishavlin** [comment] 2023-07-18 14:15
thanks for the extra info, @Ecskrabacz10 !

And after reading through, I don't actually think my PR will fully solve your problem -- that PR simply adds code to avoid yt's selection routines when using `all_data` (and simply returns all the data immediately). So since you've somehow ended up with more particles that you started with, I suspect that my PR will still load those in. 

One thing you could do that would help isolate the issue: when you call `save_as_dataset`, the file that is saved is simply another hdf file. So you could try opening that file with `h5py` to inspect the data in order to check whether the duplication is happening on initial `save_as_dataset` or on re-load.

**Comment by matthewturk** [comment] 2023-07-18 14:16
You could also post the output of `h5ls -r` on the file here for a quick look.

**Comment by Ecskrabacz10** [comment] 2023-07-18 16:08
Thank you both for the extra insight! Here's a snapshot of what the `h5ls -r` output of the saved files looks like.

![image](https://github.com/yt-project/yt/assets/42478452/e40f71a1-e49e-4065-8f76-9291fe464d83)

The length of each component looks correct. So, it seems that the duplication does not happen during the initial `save_as_dataset`, but instead on re-load @chrishavlin

**Comment by chrishavlin** [comment] 2023-07-19 18:52
Interesting. It is suspicious that the counts are off by a factor of 32 and the dataset index gets initialized with 32 chunks... maybe each chunk is referencing the same index range and everything is getting loaded 32 times... Let me look a bit more at how all that works to see if I can reproduce this behavior with a smaller dataset.

**Comment by Ecskrabacz10** [comment] 2023-07-20 16:46
I was curious and wanted to check if this problem was due to the number of CPUs in the node that I have been using. I tested two different nodes, one with 16 CPUs and one with 20. After saving and loading the same dataset from the two different nodes, both saved datasets encountered the same factor of 32 problem.

**Comment by matthewturk** [comment] 2023-07-20 22:54
This really is very confusing.  One thing that might help -- do any ewah files get generated?  If so, can you send them, and also send us the ewah files from the original pre-save-dataset dataset?

**Comment by chrishavlin** [comment] 2023-07-21 23:00
OK, was able to reproduce this on main with a simple example:

```python
import yt
import numpy as np

n_particles = int(1e6)
ppx, ppy, ppz = np.random.random(size=[3, n_particles])
ppm = np.arange(0, n_particles)
data = {
    "particle_position_x": ppx,
    "particle_position_y": ppy,
    "particle_position_z": ppz,
    "particle_mass": ppm,
}


ds = yt.load_particles(data)
ad = ds.all_data()

fn= ad.save_as_dataset('/var/tmp/test_save', fields=ds.field_list)
ds1 = yt.load(fn)
ad1 = ds1.all_data()

n_particles_out = ad1[('all', 'particle_mass')].shape[0]
print(n_particles_out, n_particles_out == n_particles, n_particles_out / n_particles)
```

prints out 

```
yt : [INFO     ] 2023-07-21 17:52:04,155 Parameters: current_time              = 0.0
yt : [INFO     ] 2023-07-21 17:52:04,155 Parameters: domain_dimensions         = [1 1 1]
yt : [INFO     ] 2023-07-21 17:52:04,156 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2023-07-21 17:52:04,157 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2023-07-21 17:52:04,157 Parameters: cosmological_simulation   = 0
yt : [INFO     ] 2023-07-21 17:52:04,158 Allocating for 1e+06 particles
yt : [INFO     ] 2023-07-21 17:52:04,557 Saving field data to yt dataset: /var/tmp/test_save.h5.
yt : [INFO     ] 2023-07-21 17:52:04,924 Parameters: current_time              = 0.0 code_time
yt : [INFO     ] 2023-07-21 17:52:04,924 Parameters: domain_dimensions         = [1 1 1]
yt : [INFO     ] 2023-07-21 17:52:04,925 Parameters: domain_left_edge          = [0. 0. 0.] code_length
yt : [INFO     ] 2023-07-21 17:52:04,926 Parameters: domain_right_edge         = [1. 1. 1.] code_length
yt : [INFO     ] 2023-07-21 17:52:04,926 Parameters: cosmological_simulation   = 0
yt : [INFO     ] 2023-07-21 17:52:04,943 Allocating for 3e+06 particles
Initializing coarse index : 100%|█████████████████████████████████████████████| 4/4 [00:00<00:00, 2488.83it/s]
Initializing refined index: 100%|█████████████████████████████████████████████| 4/4 [00:00<00:00, 2351.07it/s]

4000000 False 4.0
```

So I ended up with 4 times more particles. Furthermore, cause I gave the `particle_mass` field unique values, we can see that the data is indeed duplicated:

```python
print(np.unique(ad1[('all','particle_mass')]).shape)
```
prints `(1000000,)` (the proper size). 

This only happens with there are enough particles to trigger the chunking -- smaller initial `n_particles` don't build an `.ewah` file. 

So, not sure what the problem is yet, but we now have a simpler toy problem to debug.

**Comment by chrishavlin** [comment] 2023-07-21 23:01
I'm gonna go ahead and label this a bug at this point ...

**Comment by chrishavlin** [comment] 2023-07-21 23:09
Oh -- might be that stream dataset always uses 1 chunk, but that info is not being passed out to the saved dataset so that when it gets loaded back in the particle index re-builds with multiple chunks??

**Comment by chrishavlin** [comment] 2023-07-24 14:55
The number of chunks is related to the length of the arrays when re-loading. And it only happens on re-load because when loading back in from a dataset that was created with `save_as_dataset`, yt uses a slightly different dataset type internally to handle it. e.g., the default chunksize is 64^3, and so when reloading it should process arrays with chunks of size 64^3. But instead it seems to be cycling through chunks and loading the **entire** array each time. 

I just found the spot in the code where this is happening, so hoping can have it in today.

**Comment by chrishavlin** [comment] 2023-07-24 14:56
(and don't worry about uploading the .ewah files )

**Comment by Ecskrabacz10** [comment] 2023-07-24 16:07
Just installed the fix and it seems like it worked! It still loads the particles in 32 chunks; however, it has the same number of particles as the original dataset.

This may just be because it's a new fix but I wanted to bring it up nonetheless:
When importing ytree with the fix, it results in the following error

```
ImportError: cannot import name 'validate_index_order' from 'yt.data_objects.static_output' (/anaconda3/envs/testing/lib/python3.11/site-packages/yt/data_objects/static_output.py)
```

Once again, not too big of an issue, but I wanted to bring it up just in case.

**Comment by chrishavlin** [comment] 2023-07-24 16:12
great! 

I think the second error is already fixed by `ytree` (https://github.com/ytree-project/ytree/pull/162), so you'll want to update `ytree` to use the fix here. Doesn't look like that bug fix in `ytree` has made it to a release yet, so you'd need to install `ytree` from source.

**Comment by chrishavlin** [comment] 2023-07-24 16:13
Oh and how's the load time? much faster I hope??

**Comment by Ecskrabacz10** [comment] 2023-07-24 16:55
Ah okay that makes sense, thank you so much! And yes it is MUCH faster now, about 5 seconds to load each field instead of the 2-3 minutes it was taking before.

**Closed** 2023-07-24 17:13 UTC
Labels: bug, performance, index: particle
