### ISSUE TITLE
BUG: new error in cartopy image tests

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4540] opened 2023-06-26 09:52 UTC
### Bug report

**Bug summary**

All cartopy image tests have started failing on all PRs today, and choke on the following error
```
ValueError: 'x' must be finite, check for nan or inf values
```

I don't know yet what in the environment changed overnight, but we can exclude cartopy itself as well as its direct dependencies, none of which received a new release since yesterday.

**Comment by neutrinoceros** [comment] 2023-06-26 15:56
In #4541 I found that the change is that scipy 1.11 now invalidates nans in a kdtree queries (https://github.com/scipy/scipy/pull/18502)

Here's a "minimal" reproducer:

```python
import yt
from yt.testing import fake_amr_ds

ds = fake_amr_ds(geometry="geographic")
field = ("stream", "Density")
sl = yt.SlicePlot(ds, "altitude", field, origin="native")
sl.set_mpl_projection("PlateCarree")
sl.render()
sl.plots[field].figure.savefig("/tmp/test.png")
```

From where I'm standing now, it looks like the invalid data (nans) is generated from within cartopy, in which case the next step would be to try and eliminate yt from the minimal reproducer and see what happens.

**Comment by neutrinoceros** [comment] 2023-06-26 16:49
here's a yt-less reproducer
```python
import matplotlib.pyplot as plt
import numpy as np
from cartopy import crs as ccrs

data = [[0, 1], [0, 1]]
fig = plt.figure()
ax = fig.add_axes(
    (0, 0, 1, 1),
    projection=ccrs.Mollweide(),
)
ax.imshow(
    data,
    transform=ccrs.PlateCarree(),
)
```

Now I need to now wether it makes sense to combine `Mollweide` projection with `PlateCarree` transform, my gut says "no way" but I'm not an expert. In any case this is what yt is currently doing.

**Comment by chrishavlin** [comment] 2023-06-26 17:01
In principle there's not a problem with using a `PlateCarree` transform and `Mollweide` projection. in cartopy: 

> The projection argument is used when creating plots and determines the projection of the resulting plot (i.e. what the plot looks like). The transform argument to plotting functions tells Cartopy what coordinate system your data are defined in.

I suspect those nan's have always been there, and it's the scipy change that's exposing it now. I'll have some time this afternoon to look closely!

**Comment by neutrinoceros** [comment] 2023-06-26 17:35
Thank you ! If you think this usage is legitimate, we should probably upstream to cartopy. I can do it in half an hour

**Comment by chrishavlin** [comment] 2023-06-26 17:48
is your yt-less reproducer throwing an error for you?

**Comment by chrishavlin** [comment] 2023-06-26 17:48
(it's not for me right now... maybe my environment is not right)

**Comment by neutrinoceros** [comment] 2023-06-26 17:56
It is. Note that I couldn't reproduce at first with my usual yt-dev env, but I managed with a fresh one, no idea why.

**Comment by neutrinoceros** [comment] 2023-06-26 18:17
reported upstream as https://github.com/SciTools/cartopy/issues/2199

**Comment by neutrinoceros** [comment] 2023-06-27 09:21
not a blocker anymore (addressed by the temporary patch #4541), but we'll keep this issue open while we wait for a new cartopy release that adresses the compatibility issue and allows us to revert #4541

**Comment by chrishavlin** [comment] 2023-07-03 15:32
though now that i hit "comment" I realized that since we're using this in image tests, it is possible that there'd still be failures if the two kdtree approaches returned slightly different results... anyway... just an option to be aware of.

**Comment by chrishavlin** [comment] 2023-07-14 18:02
Upstream fix is in! Not sure on release timeline.

**Comment by neutrinoceros** [comment] 2023-07-14 19:58
Removing the warning filter isn't urgent, and I think we can close this now. Thanks @chrishavlin

**Closed** 2023-07-14 19:58 UTC
Labels: bug, tests: running tests
