### ISSUE TITLE
yt hanging in parallel over several machines

### ISSUE THREAD

**Issue by maxbeegee** [yt-project/yt#1672] opened 2018-01-18 18:50 UTC
### Bug report

**Bug summary**

yt hanging over several machines. The code runs fine on one node.

**Code for reproduction**

```python
import numpy as np
import os, sys, glob
import yt
yt.enable_parallelism()

import logging
fmt = '[%(levelname)s] %(asctime)-8s %(message)s'
logging.basicConfig(level=logging.DEBUG,
                    format=fmt,
                    datefmt='%H:%M:%S')    
del fmt

def main():
    if len(sys.argv) < 2:
        logging.error("Too few parameters. ")
        logging.info("Usage: distribution.py `filelst`.")
        sys.exit(-1)

    if '*' in sys.argv[1]:
        fnlst = glob.glob(sys.argv[1])
    else:
        fnlst = sys.argv[1:]

    storage = {}
    for sto, cfn in yt.parallel_objects(fnlst, storage = storage):
        logging.info(">>>>  %s", cfn)

        sto.result_id = cfn
        sto.result = { 'dat' : np.random.random() }

        logging.info(">>>> Done computing distributions for %s", cfn)

    logging.info(">>> Done with loop.") # <-- never reaches this line!

    if yt.is_root():
        logging.info("Gathering all data.")
        for i, (fn, vals) in enumerate(sorted(storage.items())):
            if vals is None:
                continue
            print i, fn, vals


    logging.info("Done with all.")
    
if __name__ == '__main__':
    main()
```

**Actual outcome**

```
yt : [INFO     ] 2018-01-18 09:21:25,391 Global parallel computation enabled: 0 / 10
yt : [INFO     ] 2018-01-18 09:21:25,391 Global parallel computation enabled: 1 / 10
yt : [INFO     ] 2018-01-18 09:21:25,393 Global parallel computation enabled: 5 / 10
yt : [INFO     ] 2018-01-18 09:21:25,391 Global parallel computation enabled: 3 / 10
yt : [INFO     ] 2018-01-18 09:21:25,393 Global parallel computation enabled: 6 / 10
yt : [INFO     ] 2018-01-18 09:21:25,391 Global parallel computation enabled: 4 / 10
yt : [INFO     ] 2018-01-18 09:21:25,393 Global parallel computation enabled: 7 / 10
yt : [INFO     ] 2018-01-18 09:21:25,391 Global parallel computation enabled: 2 / 10
yt : [INFO     ] 2018-01-18 09:21:25,393 Global parallel computation enabled: 8 / 10
yt : [INFO     ] 2018-01-18 09:21:25,393 Global parallel computation enabled: 9 / 10
[INFO] 09:21:25 >>>>  0003
[INFO] 09:21:25 >>>>  0004
[INFO] 09:21:25 >>>>  0005
[INFO] 09:21:25 >>>>  0000
[INFO] 09:21:25 >>>>  0006
[INFO] 09:21:25 >>>>  0001
[INFO] 09:21:25 >>>>  0007
[INFO] 09:21:25 >>>>  0002
[INFO] 09:21:25 >>>>  0008
[INFO] 09:21:25 >>>>  0009
[INFO] 09:21:25 >>>> Done computing distributions for 0005
[INFO] 09:21:25 >>>> Done computing distributions for 0006
[INFO] 09:21:25 >>>> Done computing distributions for 0007
[INFO] 09:21:25 >>>> Done computing distributions for 0008
[INFO] 09:21:25 >>>> Done computing distributions for 0009
[INFO] 09:21:25 >>>> Done computing distributions for 0000
[INFO] 09:21:25 >>>>  0010
[INFO] 09:21:25 >>>> Done computing distributions for 0001
[INFO] 09:21:25 >>>> Done computing distributions for 0010
[INFO] 09:21:25 >>>> Done computing distributions for 0002
[INFO] 09:21:25 >>>> Done computing distributions for 0003
[INFO] 09:21:25 >>>> Done computing distributions for 0004
```
(the code hangs after this)

**Expected outcome**

To finish the script.

**Version Information**

  * Operating System:
  * Python Version: python/2.7.13
  * yt version: yt version 3.5.dev0 (installed via anaconda)
  * Other Libraries (if applicable): Intel MPI 17.0.3

**Comment by maxbeegee** [comment] 2018-01-18 18:51
Note that everything runs fine with Intel MPI 18.0

**Comment by ngoldbaum** [comment] 2018-06-26 19:09
I'm not able to reproduce this so I'm closing the issue. If you are still having trouble with this please let us know. If you could, please make an example that one of us can run locally so we can reproduce the exact issue you're having.

**Closed by ngoldbaum** 2018-06-26 19:09 UTC

**Comment by maxbeegee** [comment] 2018-08-07 11:59
I had the same issue again, and did some more analysis. This post is just for documentation / if anybody else runs into the same trouble.

- The problem seems to arise only if the script above is run over several nodes (i.e., it runs fine with 20 processors on one node, but hangs if I run it with 20 processors on 2 nodes)
- Also, the problem seems to happen if I do not load the newest MPI version (i.e., 17.0.3 above but also 18.0.0;  it runs fine with 18.0.2)

I suspect that if there's a mismatch between the MPI version loaded and the one linked with mpi4py, this problem occurs.
