### ISSUE TITLE
Index Error updating from YT-3.4.0 to YT-3.5.1

### ISSUE THREAD

**Issue by samlelouch** [yt-project/yt#2253] opened 2019-04-30 02:31 UTC
### Bug report

**Bug summary**

Index error after yt upgrade 

**Code for reproduction**

```
import yt
from yt.units import kpc
import matplotlib.pyplot as plt
import numpy as np
np.set_printoptions(threshold=1500)
filename="/lunarc/nobackup/users/samvad/FINAL-50-0.5/output/output_00018/info_00018.txt"
ds=yt.load(filename)

for i in sorted(ds.derived_field_list):
        print(i)
```

**Actual outcome**

```
File "fields.py", line 10, in <module>
    for i in sorted(ds.derived_field_list):
  File "yt/data_objects/static_output.py", line 216, in ireq
    self.index
  File "yt/data_objects/static_output.py", line 509, in index
    self, dataset_type=self.dataset_type)
  File "yt/frontends/ramses/data_structures.py", line 236, in __init__
    super(RAMSESIndex, self).__init__(ds, dataset_type)
  File "yt/geometry/geometry_handler.py", line 50, in __init__
    self._setup_geometry()
  File "yt/geometry/oct_geometry_handler.py", line 25, in _setup_geometry
    self._initialize_oct_handler()
  File "yt/frontends/ramses/data_structures.py", line 245, in _initialize_oct_handler
    for i in cpu_list]
  File "yt/frontends/ramses/data_structures.py", line 245, in <listcomp>
    for i in cpu_list]
  File "yt/frontends/ramses/data_structures.py", line 82, in __init__
    self._read_amr_header()
  File "yt/frontends/ramses/data_structures.py", line 141, in _read_amr_header
    hvals.update(f.read_attrs(header))
  File "yt/utilities/cython_fortran_utils.pyx", line 223, in yt.utilities.cython_fortran_utils.FortranFile.read_attrs
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Expected outcome**

has to print the fields in the data. Was working with yt 3.4.0

**Version Information**

  * Operating System: Mac
  * Python Version: 3.6
  * yt version: 3.5.1
  * Other Libraries (if applicable): 

installed Anaconda separately and then did conda installation of YT using 'forge'

**Comment by munkm** [comment] 2019-05-08 15:16
@samlelouch it looks like maybe the header file is smaller than expected. Would you mind attaching the header file somewhere so we can take a look at it? 

@cphyc does any of this look like something you've seen before?

**Comment by cphyc** [comment] 2019-05-08 15:30
It looks like the issue reported on the mailing list (https://mail.python.org/archives/list/yt-users@python.org/thread/WKNKCY42XY5U47T4KB6A4DYZU6IHIO57/#7JFWLVJIVRYZHSUN6MFQTQZ7BVGYE2GC). 

@samlelouch could you upload the file `output_00018/amr_00018.out00001`? If this is indeed the same issue as reported by Vadlamani Samhitha then I'd guess it is due to commit 016c7e04bdf443d16b0431369be364dbb152e4ed.

**Comment by samlelouch** [comment] 2019-05-08 15:32
Hi, yes the same issue. I’m looking at your suggestion in slack help and
will get back as soon as I incorporate the changes. Thank you very much :)

**Comment by cphyc** [comment] 2019-05-08 15:33
For the record, I have suggested the following patch
```
From 3526ad0f76cccff9825f4ee25b5a8758fa45c48b Mon Sep 17 00:00:00 2001
From: Corentin Cadiou <contact@cphyc.me>
Date: Sun, 5 May 2019 19:02:08 +0200
Subject: [PATCH 1/2] quick fix

---
 yt/frontends/ramses/data_structures.py | 1 +
 yt/frontends/ramses/definitions.py     | 3 ++-
 2 files changed, 3 insertions(+), 1 deletion(-)

diff --git a/yt/frontends/ramses/data_structures.py b/yt/frontends/ramses/data_structures.py
index c5802cbba..12979474e 100644
--- a/yt/frontends/ramses/data_structures.py
+++ b/yt/frontends/ramses/data_structures.py
@@ -139,6 +139,7 @@ class RAMSESDomainFile(object):
 
         for header in ramses_header(hvals):
             hvals.update(f.read_attrs(header))
+        f.seek(4+8+4)  # skip reading of mass_sph
         # For speedup, skip reading of 'headl' and 'taill'
         f.skip(2)
         hvals['numbl'] = f.read_vector('i')
diff --git a/yt/frontends/ramses/definitions.py b/yt/frontends/ramses/definitions.py
index 9cc8278ed..a3235580a 100644
--- a/yt/frontends/ramses/definitions.py
+++ b/yt/frontends/ramses/definitions.py
@@ -42,7 +42,8 @@ def ramses_header(hvals):
                  ('stat', 3, 'd'),
                  ('cosm', 7, 'd'),
                  ('timing', 5, 'd'),
-                 ('mass_sph', 1, 'd') )
+                 #('mass_sph', 1, 'd') 
+                 )
     yield next_set
 
 field_aliases = {
-- 
2.21.0


From 0bf682b9922945ae2039622e88527146fe74eaab Mon Sep 17 00:00:00 2001
From: Corentin Cadiou <contact@cphyc.me>
Date: Wed, 8 May 2019 17:31:56 +0200
Subject: [PATCH 2/2] dont forget whence param

---
 yt/frontends/ramses/data_structures.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/yt/frontends/ramses/data_structures.py b/yt/frontends/ramses/data_structures.py
index 12979474e..05a627e17 100644
--- a/yt/frontends/ramses/data_structures.py
+++ b/yt/frontends/ramses/data_structures.py
@@ -139,7 +139,7 @@ class RAMSESDomainFile(object):
 
         for header in ramses_header(hvals):
             hvals.update(f.read_attrs(header))
-        f.seek(4+8+4)  # skip reading of mass_sph
+        f.seek(4+8+4, 1)  # skip reading of mass_sph
         # For speedup, skip reading of 'headl' and 'taill'
         f.skip(2)
         hvals['numbl'] = f.read_vector('i')
-- 
2.21.0

```

**Comment by cphyc** [comment] 2019-05-08 15:40
@samlelouch also a quick question: do you know if your cluster is big- or little-endian?

**Comment by cphyc** [comment] 2019-05-08 15:57
Another question: in `amr/output_amr.f90` do you have *exactly* the same lines? Especially the one reading `mass_sph`
```
  open(unit=ilun,file=fileloc,form='unformatted')
  ! Write grid variables
  write(ilun)ncpu
  write(ilun)ndim
  write(ilun)nx,ny,nz
  write(ilun)nlevelmax
  write(ilun)ngridmax
  write(ilun)nboundary
  write(ilun)ngrid_current
  write(ilun)boxlen
  ! Write time variables
  write(ilun)noutput,iout,ifout
  write(ilun)tout(1:noutput)
  write(ilun)aout(1:noutput)
  write(ilun)t
  write(ilun)dtold(1:nlevelmax)
  write(ilun)dtnew(1:nlevelmax)
  write(ilun)nstep,nstep_coarse
  write(ilun)einit,mass_tot_0,rho_tot
  write(ilun)omega_m,omega_l,omega_k,omega_b,h0,aexp_ini,boxlen_ini
  write(ilun)aexp,hexp,aexp_old,epot_tot_int,epot_tot_old
  write(ilun)mass_sph
  ! Write levels variables
  write(ilun)headl(1:ncpu,1:nlevelmax)
  write(ilun)taill(1:ncpu,1:nlevelmax)
  write(ilun)numbl(1:ncpu,1:nlevelmax)
  write(ilun)numbtot(1:10,1:nlevelmax)
```

**Comment by samlelouch** [comment] 2019-05-08 16:10
Hey, It's little endian and that part of my patch looks like the following:

open(unit=ilun,file=fileloc,form='unformatted')
>
>   ! Write grid variables
>
>   write(ilun)ncpu
>
>   write(ilun)ndim
>
>   write(ilun)nx,ny,nz
>
>   write(ilun)nlevelmax
>
>   write(ilun)ngridmax
>
>   write(ilun)nboundary
>
>   write(ilun)ngrid_current
>
>   write(ilun)boxlen
>
! Write time variables

  write(ilun)noutput,iout,ifout

  write(ilun)tout(1:noutput)

  write(ilun)aout(1:noutput)

  write(ilun)t

  write(ilun)dtold(1:nlevelmax)

  write(ilun)dtnew(1:nlevelmax)

  write(ilun)nstep,nstep_coarse

  write(ilun)const,mass_tot_0,rho_tot

  write(ilun)omega_m,omega_l,omega_k,omega_b,h0,aexp_ini,boxlen_ini

  write(ilun)aexp,hexp,aexp_old,epot_tot_int,epot_tot_old

!!! FlorentR - PATCH MSA

  write(ilun)!mass_sph

!!! FRenaud

  ! Write levels variables

  write(ilun)headl(1:ncpu,1:nlevelmax)

  write(ilun)taill(1:ncpu,1:nlevelmax)

  write(ilun)numbl(1:ncpu,1:nlevelmax)

>   write(ilun)numbtot(1:10,1:nlevelmax)

**Comment by cphyc** [comment] 2019-05-08 16:23
Alright, I understood what the issue is. 
The problem is that yt is expecting to read `mass_sph` as an 8-byte long double, but since the part that writes `mass_sph` is commented out, there's an empty record instead.

 So the fix is just to instruct yt that this field is optional.

**Comment by cphyc** [comment] 2019-05-08 16:24
@samlelouch if you can provide a smallish dataset produced using your version of Ramses, that would be handy to test the new code. Meanwhile, you can try out the version I pushed for PR #2259 and tell me if this solves your issue.

**Comment by samlelouch** [comment] 2019-05-08 17:04
output_00003.zip
<https://drive.google.com/file/d/1KFp-R49vzLZPZ4SeYINJJxUwWRoEACNl/view?usp=drive_web>
sure and here's one of the outputs. Thank you. Let me know if it's
accessible

**Comment by cphyc** [comment] 2019-05-09 08:28
On my local machine with #2259 , I can now load your dataset (I couldn't on the master branch) and make a plot out of it 
![info_00003_Slice_z_density](https://user-images.githubusercontent.com/5411875/57438844-1872d700-7245-11e9-8b31-746a0cf7dc96.png)

Would you mind me uploading your dataset to http://yt-project.org/data/ (it would become publicly available) for testing purposes?

**Comment by cphyc** [comment] 2019-05-09 14:45
Alternatively could you run one of the super simple test in the RAMSES folder (for example `namelist/sedov3d.nml`) and send us the first output?

**Comment by samlelouch** [comment] 2019-05-09 14:45
Thank you, you could upload the dataset.

**Comment by cphyc** [comment] 2019-05-10 09:40
Uploaded on https://github.com/yt-project/website/pull/59! Once #2259 is merged, you should be able to read again your datasets. Sorry for the trouble!

**Closed** 2019-05-10 12:57 UTC
Labels: code frontends, needs example
