### ISSUE TITLE
Add "north_vector" to field parameters

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1345] opened 2017-04-11 19:37 UTC
Originally reported by: **Anonymous**

----------------------------------------

When I try to add/create fields for my dataset, I cannot call: 

```
def _velocity_projected_north(field, data):
       nv = data.get_field_parameter("north_vector")
       .........
       return v


ds.add_field(('gas','velocity_projected_north'), function=_velocity_projected_north,units="cm/s", force_override = True)
```

It would be great if north_vector is included in dataset

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1345

**Comment by ngoldbaum** [comment] 2017-05-04 00:01
Getting this to work will require a bigger refactoring of field parameters. Marking as duplicate of #927

**Comment by ngoldbaum** [comment] 2017-05-04 00:23
Matt asked me to reopen this.

**Comment by MatthewTurk** [comment] 2017-05-16 15:43
After looking into this, I *believe* that it's already solved by the inclusion of the `cp_x_vec` and `cp_y_vec` field paramters.  I apologize for the noise, and I am closing it.

**Closed by MatthewTurk** 2017-05-16 15:43 UTC
Labels: enhancement
