### ISSUE TITLE
Projection artifacts in demeshening

### ISSUE THREAD

**Issue by qobilidop** [yt-project/yt#1480] opened 2017-07-05 15:49 UTC
### Bug report

This is concerning the [demeshening branch](https://github.com/ngoldbaum/yt/tree/sph-viz).

**Bug summary**

In this specific example, the z-axis projection shows artifacts, but the other two axes are fine. However, this could happen for any axis as discussed in the threads below.

**Code for reproduction**

```python
import yt

ds = yt.load('FIRE_M12i_ref11/snapshot_600.hdf5')
_, center = ds.find_max(('PartType0', 'density'))

p = yt.ProjectionPlot(ds, 'z', ('gas', 'density'),
                      center=center, width=(200, 'kpc'))
p.save()
```

**Actual outcome**

![snapshot_600_projection_z_density](https://user-images.githubusercontent.com/5176695/27872615-28b0105a-615e-11e7-8b78-07cbe3d801ba.png)

**Expected outcome**

As a comparison, the current octree version gives:

![snapshot_600_projection_z_density](https://user-images.githubusercontent.com/5176695/27872705-835fa362-615e-11e7-81e2-261e52461f65.png)

**Version Information**
  * Operating System: macOS 10.12.5
  * Python Version: 3.6.1
  * yt version: [demeshening](https://github.com/ngoldbaum/yt/commit/93a3dd8067bcc5b5bc028d0fdc9edd56840d6f22)
  * Other Libraries (if applicable): None

**Comment by ngoldbaum** [comment] 2017-07-05 17:02
I think this has to be a bug in the bitmap indexing. Here's a somewhat simpler test script that illustrates the issue:

```
import yt
from yt.units import kpc
from matplotlib import pyplot as plt

ds = yt.load('FIRE_M12i_ref11/snapshot_600.hdf5')

le = ds.arr([29174.11982139, 30937.3146523, 0.], 'code_length')
re = ds.arr([29398.05782139, 31161.2526523, 60000.], 'code_length')
center = ds.arr([29286.08882139, 31049.2836523, 32589.6011906], 'code_length')

reg_good = ds.region(left_edge=le, right_edge=re, center=center)

reg_bad = ds.region(left_edge=le+0.5*kpc, right_edge=re-0.5*kpc, center=center)

print(reg_good['PartType1', 'particle_position_x'].shape)
print(reg_bad['PartType1', 'particle_position_x'].shape)

for reg, value in zip((reg_good, reg_bad), ('good', 'bad')):

    px = reg['PartType1', 'particle_position_x']
    py = reg['PartType1', 'particle_position_y']

    plt.plot(px, py, '.', alpha=0.1, markerfacecolor='blue')

    plt.savefig('ppos_{}.png'.format(value))

    plt.clf()
```

This produces the following two images:

![ppos_good](https://user-images.githubusercontent.com/3126246/27875671-b764cc80-6179-11e7-9181-f17584f01577.png)

![ppos_bad](https://user-images.githubusercontent.com/3126246/27875674-bbe0261a-6179-11e7-934c-dc0dcf0edf82.png)

Something is going haywire in the particle selection for the "bad" region. While the original issue triggered this with SPH particles, I'm also able to trigger it using N-body particles in this example.

Ping @cfh5058

**Comment by chummels** [comment] 2018-03-23 03:03
After talking with @ngoldbaum about this problem, he pointed out one hacky solution.  When one takes a projection and sets a width, yt automatically creates a YTRegion object to act as a data_source in the projection.  By modifying yt so that it *does not* make a YTRegion and just uses all of the data for the projection, it avoids this issue.  

That said, the problem still exists for projections with any `data_source` being set, but this solution at least gets around part of the problem?  The patch for this behavior is a one-line change:

```
From ed08f9b2867c671877c5f3b0322130e7caa9fbc1 Mon Sep 17 00:00:00 2001
From: Cameron Hummels <chummels@gmail.com>
Date: Thu, 22 Mar 2018 19:51:07 -0700
Subject: [PATCH] A minor tweak to avoid making secondary data_sources in
 demesh projections.

---
 yt/geometry/coordinates/cartesian_coordinates.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/yt/geometry/coordinates/cartesian_coordinates.py b/yt/geometry/coordinates/cartesian_coordinates.py
index ebf347fb3..91ad0404a 100644
--- a/yt/geometry/coordinates/cartesian_coordinates.py
+++ b/yt/geometry/coordinates/cartesian_coordinates.py
@@ -281,7 +281,7 @@ class CartesianCoordinateHandler(CoordinateHandler):
                 bnds = data_source.ds.arr(
                     bounds, 'code_length').in_units('cm').tolist()
                 buff = np.zeros(size, dtype='float64')
-                for chunk in proj_reg.chunks([], 'io'):
+                for chunk in data_source.ds.all_data().chunks([], 'io'):
                     data_source._initialize_projected_units([field], chunk)
                     pixelize_sph_kernel_projection(
                         buff,
--
2.13.3```

**Comment by chummels** [comment] 2018-03-23 03:04
And the corresponding z-projection: 

![snapshot_600_projection_z_density](https://user-images.githubusercontent.com/8250999/37809369-41cf6948-2e0c-11e8-9d33-bc79d7a0b502.png)

**Comment by ngoldbaum** [comment] 2018-03-23 14:24
@matt yes that’s what [my comment](https://github.com/yt-project/yt/issues/1480#comment-313164896) illustrates.

**Comment by MatthewTurk** [comment] 2018-03-23 14:35
@ngoldbaum ugh, I missed you were using `plt.plot` rather than `proj.plot`, my mistake.

**Comment by ngoldbaum** [comment] 2018-03-23 14:39
Meagan and I looked at this at SciPy last year, concluded it was a bug in the bitmap selection, and didn’t get much further than that. Unfortunately basically only Meagan understands that code well and it’s been a while since she wrote it :/

**Comment by MatthewTurk** [comment] 2018-03-23 15:25
@ngoldbaum @langmm Do you have any idea if it preferentially selects one axis over another, or is it *any* bitmap operation?  Is it just region selectors, or any selectors?

**Comment by ngoldbaum** [comment] 2018-03-23 15:28
I've only seen it with region selectors but it might happen with other selectors, I haven't extensively tested. I'm not sure if it preferentially selects any axis - I guess I'm not sure what you mean by that exactly.

I think the visual pattern of data that shows up in the projections comes from Gadget's Hilbert load balancing and not from any spatial structure yt's bitmap index, although the bitmap index is screwing up in a way that you can see the load balancing pattern visually.

**Comment by chummels** [comment] 2018-04-21 08:06
Just as a followup on this, the frequency of this bug is high in the datasets I'm using (FIRE).  I know there was some comments offline about this potentially being a rare problem.  As an example, here is a movie of a series of consecutive projections using a `width` and thus a region selector from one of the FIRE datasets.  As you can see, the artifacts are present in 25-50% of the frames.  Notably, these are ProjectionPlots of the density field on the 'x' axis of these datasets.

![density](https://user-images.githubusercontent.com/8250999/39081969-fd33116c-44ff-11e8-991d-a23c364b0c21.gif)

**Comment by ngoldbaum** [comment] 2018-04-21 13:24
@chummels is this with the workaround you implemented so the projections are using all_data under the hood?

My understanding was that you had an acceptable workaround.

I realize that this is a big problem and needs to be fixed. The problem is it’s likely in very low level code that I don’t understand very well and it will take sustained effort on someone’s part to fix it. I simply haven’t been able to allocate a significant chunk of time to work on this.

**Comment by chummels** [comment] 2018-04-21 14:49
These results come from when I'm not using the solution I proposed above.  That solution works fairly well in the context of projecting with a width (although not ideally for actual science because you get foreground and background material in your images).  But for anyone actually wanting to use a `data_source` in a projection, my movie was just to demonstrate that the problem is pretty widespread and not just from an occasional irregular dataset.

I understand it is a difficult bug to fix based on where it sits in the codebase, and I'm not asking you to fix it immediately.  Again, the last time we talked, you thought this was just a one-off problem that rarely came up, and I just wanted to give evidence that it happens pretty frequently and may hit other people's workflows pretty often as well.  If I can help in resolving this, let me know.

**Comment by ngoldbaum** [comment] 2018-04-21 14:52
> although not ideally for actual science because you get foreground and background material in your images

This is how projections work for AMR data as well if you just specify a `width`. Maybe you want to specify a `depth` as well?

**Comment by qobilidop** [comment] 2018-04-21 23:01
@chummels as a workaround, I've been experimenting with cutting out the interested particles into a separate snapshot and only do analysis on `all_data()` of the reloaded snapshot. Below is a script to demonstrate the workflow:
```python
import numpy as np
import h5py
import yt

def save_as_gadget_dataset(ds, filename, fields, masks):
    ad = ds.all_data()
    num_part = np.zeros_like(ds.parameters['NumPart_Total'])
    with h5py.File(filename, 'w') as f:
        pass
    for ptype, mask in masks.items():
        for field in fields:
            if (ptype, field) in ds.field_list:
                print('Writing', ptype, field)
                with h5py.File(filename, 'a') as f:
                    dset = f.create_dataset(
                        f'{ptype}/{field}',
                        data=ad[ptype, field][mask].v
                    )
        pi = list(ds.particle_type_counts.keys()).index(ptype)
        num_part[pi] = mask.sum()
    parameters = ds.parameters
    parameters['NumPart_ThisFile'] = num_part.astype('int')
    parameters['NumPart_Total'] = num_part.astype('int')
    parameters['NumFiles'] = 1
    print('Writing Header')
    with h5py.File(filename, 'a') as f:
        grp = f.create_group('Header')
        for k, v in parameters.items():
            grp.attrs[k] = v

# Trigger the bug
ds = yt.load('FIRE_M12i_ref11/snapshot_600.hdf5')
_, center = ds.find_max(('PartType0', 'density'))
width = ds.quan(800, 'kpc')
box = ds.box(center - width * 0.5, center + width * 0.5)
yt.ProjectionPlot(ds, 'z', ('gas', 'density'), center=center, width=width, data_source=box).save()

# Make a cut snapshot of the interested region
fields = ['Coordinates', 'Density', 'Masses', 'SmoothingLength']
ad = ds.all_data()
masks = {}
ptype = 'PartType0'
masks[ptype] = (ad[ptype, 'Coordinates'] - center < width * 0.5).all(axis=1)
save_as_gadget_dataset(ds, 'cut.hdf5', fields, masks)

# Reload the cut snapshot and redo the projection
ds = yt.load('cut.hdf5')
_, center = ds.find_max(('PartType0', 'density'))
yt.ProjectionPlot(ds, 'z', ('gas', 'density'), center=center, width=width).save()
```
The results are shown below:
![snapshot_600_projection_z_density](https://user-images.githubusercontent.com/5176695/39089365-6af6257a-457a-11e8-8c43-62014188577e.png)
![cut_projection_z_density](https://user-images.githubusercontent.com/5176695/39089367-7016159c-457a-11e8-9967-430f511a652f.png)

The metalicity fields might need some special treatments, but it's totally doable.

Also, when I was discussing with @brittonsmith yesterday, he suggestted me using `save_as_dataset`. I haven't figured out a way to make it work with projections yet. If it works out, the process could be even simpler.

**Comment by ngoldbaum** [comment] 2018-05-04 22:42
This also indicates that an awful, extremely hacky workaround that @chummels and @qobilidop could try is changing the default `index_order` in their call to yt.load.

**Comment by MatthewTurk** [comment] 2018-05-04 22:46
I'd caution that might result in different results on different datasets, especially since it's not obvious to me where the strange behavior comes from.

**Comment by MatthewTurk** [comment] 2018-05-04 22:49
It's also possible that it would give different results based on different regions that you selected inside the data set

**Comment by MatthewTurk** [comment] 2018-05-05 00:43
As an update, I did a comparison between the "good" and "bad" for `o1=7` (`o2=2`).  For the "good" region, these are the selected files:

`[0 1 2 3 4 6 9]`

For the bad:

`[0 1 3 4 6 9]`

Strangely enough, when selecting with `o1=4` and `o2=2`, we get these:

Good: `[0 1 2 3 4 9]`
Bad: `[0 1 2 3 4 9]`

So it seems that file ind 6 is overselected in the higher `o1`, which I need to think about.  But, it's definitely the absence of file ind 2 that causes the underselection at `o1=7`.

**Comment by MatthewTurk** [comment] 2018-05-06 23:56
I think I've tracked down the problem.  I have not yet fixed it, but will be working on that next.  I wanted to update with progress.

The issue is in the combination of how the `recursive_morton_mask` function works for `nlevel == self.order1` when `sbbox == 1`, I believe.  In this case, `is_refined` is set, and we add the coarse selection marker for `mi1`.  But, when doing the actual intersection calculation, we use the `logicalxor` of the refinement and the coarse -- so in this case, we're both refined *and* we have the coarse cell selected, so it doesn't show up as being selected in the intersection function.

I'm working through right now whether or not the correct behavior can be obtained with changing the `logicalxor` to `logicalor` ; for this particular test case it seems to, but there's of course the possibility that this would lead to overselection in other cases, and too much IO.  I cannot *immediately* see the issue with changing this, but I am not certain I have considered all possibilities yet.

I've tried a few things like modifying the behavior to select subcells for mi1 in the case that `sbbox == 1`, but they did not immediately work.  I'll be exploring other options later tonight.

(ping @langmm )

**Comment by MatthewTurk** [comment] 2018-05-06 23:58
Also, I should note that the *specific* call to `logicalxor` that I'm talking about is in the `_intersects` function in `FileBitmasks`.

**Comment by MatthewTurk** [comment] 2018-05-07 02:33
Current status, before I have to sign off for the night.  I now understand the `logicalxor` call, and believe that is correct -- apologies for doubting.

However, I have modified the `_intersects` function to now look like this for the final conditional:

```
        # Intersection at refined level
        if ewah_refn1[0].intersects(ewah_refn2[0]) == 1:
            it_map1 = ewah_coll1[0].begin()
            while (it_map1 != ewah_coll1[0].end()):
                mi1 = dereference(it_map1).first
                it_map2 = ewah_coll2[0].find(mi1)
                if it_map2 != ewah_coll2[0].end():
                    mi1_ewah1 = dereference(it_map1).second
                    mi1_ewah2 = dereference(it_map2).second
                    if mi1 == 936304:
                        print("HELLO1", ifile, mi1, mi1_ewah1.numberOfOnes(), mi1_ewah2.numberOfOnes())
                    if mi1_ewah1.intersects(mi1_ewah2):
                        return 1
                preincrement(it_map1)
```
All of the `mi1_ewah2.numberOfOnes()` are zero.  All of these may turn out to be false steps, and I am going to use this bug to track my progress, so feel free to unsubscribe if you get sick of them! 😁

**Comment by MatthewTurk** [comment] 2018-05-07 02:53
See https://github.com/ngoldbaum/yt/pull/5 for what I believe to be the solution.  I have looked through the code and not been able to find other similar usages that would result in the same problem.

**Comment by chummels** [comment] 2018-05-07 14:26
I will grab your PR and test it locally on the time series that generated the animated gif above to see if that resolves the problem in the N snapshots where the bug manifests.  I'll report back in the next day or so.  Thanks for the deep dig into this troublesome bug, @MatthewTurk !

**Comment by chummels** [comment] 2018-05-08 17:37
I went back and applied your fix (https://github.com/ngoldbaum/yt/pull/5/) in my script to generate a movie similar to the one I created above.  My script generates a series of ProjectionPlots, each looking through a time series of low-resolution FIRE datasets.  The ProjectionPlots have a `width` set, thereby creating a `region` object for the projection.  Before I applied your fix, I got this result from the tip of `sph-viz`:

![broken](https://user-images.githubusercontent.com/8250999/39772409-104dd87e-52aa-11e8-9820-939a06722150.gif)

After I applied your fix, this is what I got:

![fix](https://user-images.githubusercontent.com/8250999/39770791-e3a63456-52a4-11e8-9182-946c18ae11f0.gif)

Additionally, I tested the original usecase that @qobilidop reported.  Without the fix:

![old](https://user-images.githubusercontent.com/8250999/39773047-b93ce000-52ab-11e8-9197-38c3075a9cbc.png)

With the fix:

![snapshot_600_projection_z_density](https://user-images.githubusercontent.com/8250999/39773044-b39c87d6-52ab-11e8-971d-3d3b01b297a9.png)




So as far as my testing is concerned, this resolves the issue.  Thank you @matt for the deep dig on this!  Much appreciated!

**Comment by jzuhone** [comment] 2021-11-24 23:30
@matthewturk this is a very similar issue, no?

**Closed by jzuhone** 2021-11-24 23:30 UTC
Labels: demeshening
