### ISSUE TITLE
Grid fields in saved data object were loaded as particle fields

### ISSUE THREAD

**Issue by yihaochen** [yt-project/yt#1536] opened 2017-08-11 17:05 UTC
### Bug report

**Bug summary**
Using save_as_dataset to save a data object and reload it, grid fields were loaded as particle fields and cause error in plotting.

**Code for reproduction**

```python
import yt
ds = yt.load('IsolatedGalaxy/galaxy0030/galaxy0030')
fields = ['density']
le = ds.domain_left_edge
re = ds.domain_right_edge
box = ds.box(le, re, fields=fields)
box.save_as_dataset('galaxy0030_test.h5', fields=fields)

box_ds = yt.load('galaxy0030_test.h5')
proj = yt.ProjectionPlot(box_ds, 'z', fields)
```

**Actual outcome**

```
yt : [INFO     ] 2017-08-11 11:47:12,041 Parameters: current_time              = 0.0060000200028298
yt : [INFO     ] 2017-08-11 11:47:12,044 Parameters: domain_dimensions         = [32 32 32]
yt : [INFO     ] 2017-08-11 11:47:12,050 Parameters: domain_left_edge          = [ 0.  0.  0.]
yt : [INFO     ] 2017-08-11 11:47:12,052 Parameters: domain_right_edge         = [ 1.  1.  1.]
yt : [INFO     ] 2017-08-11 11:47:12,054 Parameters: cosmological_simulation   = 0.0
Parsing Hierarchy : 100%|██████████| 173/173 [00:00<00:00, 12662.11it/s]
yt : [INFO     ] 2017-08-11 11:47:12,097 Gathering a field list (this may take a moment.)
yt : [INFO     ] 2017-08-11 11:47:17,242 Saving field data to yt dataset: galaxy0030_test.h5.
yt : [INFO     ] 2017-08-11 11:47:17,972 Parameters: current_time              = 0.0060000200028298 code_time
yt : [INFO     ] 2017-08-11 11:47:17,975 Parameters: domain_dimensions         = [2 2 2]
yt : [INFO     ] 2017-08-11 11:47:17,978 Parameters: domain_left_edge          = [ 0.  0.  0.] code_length
yt : [INFO     ] 2017-08-11 11:47:17,982 Parameters: domain_right_edge         = [ 1.  1.  1.] code_length
yt : [INFO     ] 2017-08-11 11:47:17,986 Parameters: cosmological_simulation   = 0.0
yt : [INFO     ] 2017-08-11 11:47:18,070 Allocating for 3.644e+06 particles (index particle type 'all')
yt : [INFO     ] 2017-08-11 11:47:19,977 Identified 5.559e+05 octs

---------------------------------------------------------------------------
YTInvalidFieldType                        Traceback (most recent call last)
<ipython-input-2-3ea45efda353> in <module>()
      8 
      9 box_ds = yt.load('galaxy0030_test.h5')
---> 10 sl = yt.ProjectionPlot(box_ds, 'z', fields)

/home/ychen/src/yt-git/yt/visualization/plot_window.py in __init__(self, ds, axis, fields, center, width, axes_unit, weight_field, max_level, origin, right_handed, fontsize, field_parameters, data_source, method, proj_style, window_size, aspect)
   1436         # plotting classes to avoid an exception
   1437         test_data_source = ds.all_data()
-> 1438         validate_mesh_fields(test_data_source, fields)
   1439 
   1440         if isinstance(ds, YTSpatialPlotDataset):

/home/ychen/src/yt-git/yt/visualization/plot_window.py in validate_mesh_fields(data_source, fields)
    137 
    138     if len(invalid_fields) > 0:
--> 139         raise YTInvalidFieldType(invalid_fields)
    140 
    141 

YTInvalidFieldType: 
SlicePlot, ProjectionPlot, and OffAxisProjectionPlot can only plot fields that
are defined on a mesh, but received the following particle fields:

    [('all', 'density')]

Did you mean to use ParticlePlot or plot a deposited particle field instead?


```

**Expected outcome**

The density field should be loaded as a grid field instead of a particle field. I am not sure if it was the saving or the loading part went wrong.

**Comment by ngoldbaum** [comment] 2017-08-11 17:08
I think this is a duplicate of #1444, which should be fixed. Are you using the latest development version of yt?

**Comment by ngoldbaum** [comment] 2017-08-11 17:12
Darn, still an issue. I wonder why the fix for #1444 isn't effective here.

**Comment by yihaochen** [comment] 2017-08-11 17:13
I was using the github version last updated on Aug 3. The issue is still there.

**Comment by ngoldbaum** [comment] 2017-08-11 17:15
Oh wait, I see. You're not saving the projection. I don't think this would ever work given the way the ytdata frontend works (isn't that right @brittonsmith?).

The following *does* work however, and does what you want I think:

```
import yt
ds = yt.load('IsolatedGalaxy/galaxy0030/galaxy0030')
fields = ['density']
le = ds.domain_left_edge
re = ds.domain_right_edge
box = ds.box(le, re, fields=fields)
proj = ds.proj('density', 'z', data_source=box)
proj.save_as_dataset('galaxy0030_test.h5', fields=fields)

proj_ds = yt.load('galaxy0030_test.h5')
proj = yt.ProjectionPlot(proj_ds, 'z', fields)
```

**Comment by yihaochen** [comment] 2017-08-11 17:21
I thought that I can save a geometric data object and reload it. I am actually trying to create a derived field that need some time to calculate. So I am looking for a way to save the values of that derived field and load it later. But maybe it does not work this way.

I was looking at
http://yt-project.org/docs/dev/analyzing/objects.html#storing-and-loading-objects

> Field data can be saved to disk in a format that allows for it to be reloaded just like a regular dataset.

**Comment by ngoldbaum** [comment] 2017-08-11 17:23
Unfortunately the caveat with that statement is that the field data are saved, but we don't save the spatial grid information, so we treat the data as particle data.

I believe this limitation is discussed in the YTEP: http://ytep.readthedocs.io/en/latest/YTEPs/YTEP-0025.html#geometrical-data-containers

**Comment by yihaochen** [comment] 2017-08-11 17:31
I see. Is there any way in yt that I can save the derived field to disk to avoid calculating it every time?

**Comment by ngoldbaum** [comment] 2017-08-11 17:39
Like you're doing now if you just need the raw field values. If you need to make a projection then you're going to need to save the projected field values in a separate saved dataset.

**Comment by yihaochen** [comment] 2017-08-11 17:49
I wanted to save the field values so that I can do more operation on them, for example, projection at different directions. Thus, saving only the projected values does not help much in my situation.

**Comment by ngoldbaum** [comment] 2017-08-11 17:52
Maybe you want to be using the functionality to save data in the grid data format?

http://yt-project.org/docs/dev/reference/api/yt.utilities.grid_data_format.writer.html

That assumes you're working with block AMR data.

**Comment by yihaochen** [comment] 2017-08-11 18:00
That looks like what I was looking for. I will try that. Thank you so much!

**Closed** 2017-08-11 18:00 UTC
