### ISSUE TITLE
Missing Row from Projection FRB when using weight_field

### ISSUE THREAD

**Issue by laurennc** [yt-project/yt#1657] opened 2017-12-22 22:08 UTC
I’m having a minor issue generating frbs from projections with weight fields. If I pass a data source object (typically a rectangular volume) and no weight field, everything is fine with the frb. But if I add a weight field to the projection, one row of the resulting frb is full of nans.

For example:
```
obj = ds.proj(‘temperature’,index,data_source=rb,weight_field='H_nuclei_density')
frb = obj.to_frb((95,’kpc’),(20,20),center=rb_center)

obj = ds.proj(‘temperature,index,data_source=rb)
frb = obj.to_frb((95,’kpc’),(20,20),center=rb_center)
```
yields the following once the frbs are plotted:

![frb_example](https://user-images.githubusercontent.com/1873218/34313635-8c588f12-e73a-11e7-8f21-82f218c9bdaa.png)

so it's not just an issue of a mismatch between the volume I'm supplying in the data source versus the volume I'm requesting for the frb.

Any help/advice on getting this row back when using weight_field would be great! Thanks.

**Version Information**
  * Operating System: macOS 10.12.6
  * Python Version:  2.7.13
  * yt version:  3.4.0, installed with conda

**Comment by ngoldbaum** [comment] 2017-12-22 23:30
Is there any chance you can make a full runnable script that triggers this behavior? If possible use of the example datasets from yt-project.org/data. You can also share a dataset of yours that triggers this with the “yt upload” command line helper.

**Comment by ngoldbaum** [comment] 2018-06-26 19:36
I'm going to close this issue because there isn't a way to reproducibly trigger this behavior. If you are still running into this issue please reopen with a runnable example so we can debug the issue.

**Closed by ngoldbaum** 2018-06-26 19:36 UTC
Labels: bug, needs example
