### ISSUE TITLE
h5py throwing errors on yt-4.0 branch

### ISSUE THREAD

**Issue by munkm** [yt-project/yt#2404] opened 2019-12-19 22:40 UTC
# Bug report 

**Bug summary**

I've noticed the following errors on appveyor on all of the recent PRs that have been submitted to the `yt-4.0` branch, even those that definitely don't touch this part of the codebase (like yt-project/yt#2396). I haven't been able to reproduce it locally and I think in order to do a deeper debug I'll need to log on to the appveyor machines. 

It looks to me like in the `test_image_array_hdf5` we use `unyt/array.py` to write `d.attrs[k]=v` to hdf5 and then we get an issue from h5py. 

I'm happy to work with people to dive into this, but since it's popping up in a couple of places we should probably have an issue for it. 

```
======================================================================
ERROR: test_image_array_hdf5 (yt.data_objects.tests.test_image_array.TestImageArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\yt\yt\data_objects\tests\test_image_array.py", line 71, in test_image_array_hdf5
    im_arr.save('test_3d_ImageArray', png=False)
  File "C:\projects\yt\yt\data_objects\image_array.py", line 385, in save
    self.write_hdf5("%s.h5" % filename, dataset_name)
  File "C:\projects\yt\yt\data_objects\image_array.py", line 112, in write_hdf5
    info=self.info)
  File "C:\Miniconda36-x64\envs\test\lib\site-packages\unyt\array.py", line 1347, in write_hdf5
    d.attrs[k] = v
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Miniconda36-x64\envs\test\lib\site-packages\h5py\_hl\attrs.py", line 100, in __setitem__
    self.create(name, data=value)
  File "C:\Miniconda36-x64\envs\test\lib\site-packages\h5py\_hl\attrs.py", line 201, in create
    attr = h5a.create(self._id, self._e(tempname), htype, space)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5a.pyx", line 47, in h5py.h5a.create
RuntimeError: Unable to create attribute (object header message is too large)
======================================================================
ERROR: test_image_array_hdf5 (yt.data_objects.tests.test_image_array.TestImageArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\yt\yt\data_objects\tests\test_image_array.py", line 129, in tearDown
    shutil.rmtree(self.tmpdir)
  File "C:\Miniconda36-x64\envs\test\lib\shutil.py", line 500, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Miniconda36-x64\envs\test\lib\shutil.py", line 395, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Miniconda36-x64\envs\test\lib\shutil.py", line 393, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpa6n29kpq\\test_3d_ImageArray.h5'
----------------------------------------------------------------------
```

**Comment by ngoldbaum** [comment] 2019-12-19 23:18
I would guess you’d need a windows machine with the latest version of h5py installed to get this. Maybe an upstream change in h5py?

**Comment by matthewturk** [comment] 2019-12-19 23:51
Some preliminary digging by @Xarthisius suggests it may be because the results of the call to `np.void()` on the serialized unit registry may break the 64k mark.  It seems not ... un-plausible ... that this could be platform dependent based on things like string encoding.  Maybe?  Anyway, it seems pretty clear that we're over the limit somehow.

This is pending further investigation, but it may also be that upstream changes have pushed an edge-case usage that is a soft violation of some standard into a hard error.

If anything that is found is relevant, we should update https://github.com/h5py/h5py/issues/1053 as well.

**Comment by ngoldbaum** [comment] 2019-12-19 23:54
Please also feel free to open an issue in unyt to track this. I have a windows machine I can do some debugging on. I also suspect we can make serialized unit registries a lot slimmer by not saving default units.

For now maybe just skip this test on windows so we don't get noise on CI?

**Comment by matthewturk** [comment] 2019-12-20 18:31
For what it's worth, I reproduced this on my linux machine!

* h5py: 2.10.0
* hdf5: 1.10.5
* unyt: v2.4.0

At this point in the code, it's attempting to set the `unit_registry` attribute in `unyt/array.py:1347` in `write_array`.  This is a numpy void with dtype `|V71372`, itemsize of 71372.

I am genuinely not sure if this should be address in unyt or in yt, as if we're creating an `ImageArray` with such an enormous table of units, that also doesn't seem like the right thing to do -- or to expect unyt to deal with.

The length of `self.units.registry.lut` is 858, and the `unit_system` is:

```
mks Unit System
 Base Units:
  length: m
  mass: kg
  time: s
  temperature: K
  angle: rad
  current_mks: A
  luminous_intensity: cd
 Other Units:
  energy: J
  specific_energy: J/kg
  pressure: Pa
  force: N
  magnetic_field: T
  charge: C
  frequency: Hz
  power: W
  electric_potential: V
  capacitance: F
  resistance: Ω
  magnetic_flux: Wb
  luminous_flux: lm
```

`unit_registry_id == '0f4ede9d8faad3c5b8d78d6e51498789'`

**Comment by ngoldbaum** [comment] 2019-12-20 18:44
I think this would be fixed by implementing the suggestions in https://github.com/yt-project/unyt/issues/12. Most of that data is physical units that probably don’t need to be saved to disk.

**Closed** 2020-01-10 16:51 UTC
Labels: bug, yt core
