### ISSUE TITLE
Broken install from pypi

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3136] opened 2021-03-23 17:34 UTC
### Bug report

**Bug summary**

Installing yt 3.6.1 from pypi against a brand new environment raises
```shell
pip install yt
```
```
    ImportError: Could not import cython or numpy. Building yt from source requires
    cython and numpy to be installed. Please install these packages using
    the appropriate package manager for your python environment.
```

Numpy as and Cython should be specified as build dependencies somehow. I think this error is relevant, and meant only when one is trying to build _from source_, but certainly not from distributed packages providers.
It's too late to fix this for yt 3.6.1, though maybe the fix could be back ported to the 3.6.2 branch eventually.
I don't know how to fix it atm.

Edit: I forgot that the yt 3.6.x series doesn't include `pyproject.toml`, I think that this file already specifies the build deps and so the problem will not affect yt 4.0
This issue should be revisited _after_ the release and be either closed or hot fixed.

**Comment by munkm** [comment] 2021-03-23 17:51
Is your machine downloading the tar file or a wheel? If it is downloading the tar file your machine is trying to build from source.

**Comment by munkm** [comment] 2021-03-23 18:54
I strongly suspect you are trying to install yt with a python version that we don't have a wheel for on pypi. When this happens your machine will try build from source by donwloading the .tar file rather than the wheel. I agree that this isn't the most user friendly and we could add a note to the docs warning about it for users with the error message. I think we should close this because we don't have a broken install, this is expected behavior.

**Closed by munkm** 2021-03-23 18:54 UTC
Labels: bug, infrastructure

**Comment by neutrinoceros** [comment] 2021-03-23 18:58
Oh right, I didn't think of this. I created the env with python 3.9.1, which wasn't release at the time of yt 3.6.1, so I guess that's normal
