### ISSUE TITLE
Athena grid data: reading 2D grid data into 1D array? + memory issue

### ISSUE THREAD

**Issue by astroboylrx** [yt-project/yt#1775] opened 2018-05-05 00:29 UTC
### Bug report

**Bug summary**

After loading 2D Athena grid data, all_data() method gives me a field with 1D array.

**Code for reproduction**

When I read Athena data (one field named "dpar" at a 2D grid with 128x64 cells) from a vtk file by
```python
ds = yt.load("data.vtk")
ad = ds.all_data()
```
`ad["dpar"].shape` returns `(8192,)`. I know another way to get the correct-shaped data is `ad = ds.index.grids[0]` and then `ad["dpar"].shape` will return `(128, 64, 1)`.

I wonder if it is designed in that way?

Digging into the code, I found this line
https://github.com/yt-project/yt/blob/657f47c63cbd049d9bcadd9ee628e40b222cbff2/yt/frontends/athena/io.py#L109
which put a correct-shaped data `ds` into the dict `rv`. 
More specifically, `ds` received `data` returned by the function `_read_chunk_data()`. According to the ipdb outupt, both `data` and `ds` has the correct shape.

```bash
ipdb> n
> ...yt/frontends/athena/io.py(83)_read_chunk_data()
     41    def _read_chunk_data(self,chunk,fields):
     ...
     82             f.close()
---> 83         return data
     84

ipdb> n
--Return--
{0: {('athena', 'dpar'): array([[[0.],...       [0.]]])}}
ipdb> until 109
ipdb> l
    104             data = self._read_chunk_data(chunk, fields)
    105             for g in chunk.objs:
    106                 for field in fields:
    107                     ftype, fname = field
    108                     ds = data[g.id].pop(field)
--> 109                     nd = g.select(selector, ds, rv[field], ind) # caches
    110                 ind += nd
    111                 data.pop(g.id)
    112         return rv
    113
    114 def get_read_table_offset(f):

ipdb> ds.shape
(128, 64, 1)
```
The debugger refused to print `rv` and returned `*** Not yet returned!`. And after that, I found `rv` is returned containing an 1D array
```bash
ipdb> n
> /Users/rixin/projects/venvs/asf/lib/python3.6/site-packages/yt/frontends/athena/io.py(112)_read_fluid_selection()
    111                 data.pop(g.id)
--> 112         return rv
    113

ipdb> n
--Return--
{('athena', 'dpar'): array([0., 0...., 0., 0., 0.])}
```

I don't quite understand the `select` function at https://github.com/yt-project/yt/blob/657f47c63cbd049d9bcadd9ee628e40b222cbff2/yt/data_objects/grid_patch.py#L402

Is there any other method that I am supposed to use to retrieve data?

**Version Information**

  * Operating System: macOS 10.13.4
  * Python Version: 3.6.5
  * yt version: 3.4.1 (installed by pip)
  * Other Libraries (if applicable):

**Comment by ngoldbaum** [comment] 2018-05-05 00:50
Is there any chance you can share a data file that triggers this behavior? You can do `yt upload data.vtk` then share the link that prints out here.

To answer your question, no, this sounds like a bug.

**Comment by jzuhone** [comment] 2018-05-05 01:10
In yt data containers (like what is returned by ds.all_data()) always return 1D arrays for fields regardless of the underlying dimensionality of the dataset. If you want to make a 2D image, you can create a slice and make a fixed resolution buffer:

https://yt-project.org/doc/visualizing/manual_plotting.html?highlight=fixed%20resolution

**Comment by astroboylrx** [comment] 2018-05-05 01:12
More on this. I also encoutered memory issue. 

I'm going through a list of vtk files to perform Fourier analyses. Every time, `yt.load()` increase the usage of memory by ~10 MiB and never collect garbage (which might in fact be Python's fault). The size of each vtk file is only 32KB! Thus, analyzing 300 files cost me ~3 GB of memory.

The following results are produced by memory_profiler.

```python
Line #    Mem usage    Increment   Line Contents
================================================
    27  131.930 MiB  131.930 MiB   @profile
    28                             def secular_radial_collapse(prefix, num_files, nwave=1):
    29  131.930 MiB    0.000 MiB       t = np.zeros(num_files)
    30  131.930 MiB    0.000 MiB       amp = np.zeros(num_files)
    31
    32  131.930 MiB    0.000 MiB       i = 0
    33                                 #ipdb.set_trace()
➜➜  34  145.250 MiB   13.320 MiB       ds = yt.load(prefix+'{:04d}'.format(i)+".dpar.vtk")
    35  145.316 MiB    0.066 MiB       dpar = (ds.index.grids[0])["dpar"].value[:, :, 0]
    36  145.336 MiB    0.020 MiB       tmp = np.fft.fft2(dpar)
    37  145.348 MiB    0.012 MiB       amp[i] = np.sum(abs(tmp[nwave::ds.domain_dimensions[0]-nwave*2, 0])) / abs(tmp[0][0])
    38  145.348 MiB    0.000 MiB       t[i] = ds.current_time
    39
    40  145.348 MiB    0.000 MiB       i = 1
➜➜  41  155.289 MiB    9.941 MiB       ds = yt.load(prefix+'{:04d}'.format(i)+".dpar.vtk")
    42  155.289 MiB    0.000 MiB       dpar = (ds.index.grids[0])["dpar"].value[:, :, 0]
    43  155.289 MiB    0.000 MiB       tmp = np.fft.fft2(dpar)
    44  155.289 MiB    0.000 MiB       amp[i] = np.sum(abs(tmp[nwave::ds.domain_dimensions[0]-nwave*2, 0])) / abs(tmp[0][0])
    45  155.289 MiB    0.000 MiB       t[i] = ds.current_time
    46
    47  155.289 MiB    0.000 MiB       i = 2
➜➜  48  166.266 MiB   10.977 MiB       ds = yt.load(prefix+'{:04d}'.format(i)+".dpar.vtk")
    49  166.266 MiB    0.000 MiB       dpar = (ds.index.grids[0])["dpar"].value[:, :, 0]
    50  166.266 MiB    0.000 MiB       tmp = np.fft.fft2(dpar)
    51  166.266 MiB    0.000 MiB       amp[i] = np.sum(abs(tmp[nwave::ds.domain_dimensions[0]-nwave*2, 0])) / abs(tmp[0][0])
    52  166.266 MiB    0.000 MiB       t[i] = ds.current_time
```

For larger vtk files (512KB), `yt.load()` consumes even more memory and increases my dynamic swap to 10+ GB. 
```python
Line #    Mem usage    Increment   Line Contents
================================================
    27  131.918 MiB  131.918 MiB   @profile
    28                             def secular_radial_collapse(prefix, num_files, nwave=1):
    29  131.918 MiB    0.000 MiB       t = np.zeros(num_files)
    30  131.918 MiB    0.000 MiB       amp = np.zeros(num_files)
    31
    32  131.918 MiB    0.000 MiB       i = 0
➜➜  33  165.160 MiB   33.242 MiB       ds = yt.load(prefix+'{:04d}'.format(i)+".vtk")
    34  165.223 MiB    0.062 MiB       dpar = (ds.index.grids[0])["dpar"].value[:, :, 0]
    35  165.738 MiB    0.516 MiB       tmp = np.fft.fft2(dpar)
    36  165.750 MiB    0.012 MiB       amp[i] = np.sum(abs(tmp[nwave::ds.domain_dimensions[0]-nwave*2, 0])) / abs(tmp[0][0])
    37  165.750 MiB    0.000 MiB       t[i] = ds.current_time
    38
    39  165.750 MiB    0.000 MiB       i = 1
➜➜  40  183.887 MiB   18.137 MiB       ds = yt.load(prefix+'{:04d}'.format(i)+".vtk")
    41  184.012 MiB    0.125 MiB       dpar = (ds.index.grids[0])["dpar"].value[:, :, 0]
    42  184.512 MiB    0.500 MiB       tmp = np.fft.fft2(dpar)
    43  184.512 MiB    0.000 MiB       amp[i] = np.sum(abs(tmp[nwave::ds.domain_dimensions[0]-nwave*2, 0])) / abs(tmp[0][0])
    44  184.512 MiB    0.000 MiB       t[i] = ds.current_time
    45
    46  184.512 MiB    0.000 MiB       i = 2
➜➜  47  212.996 MiB   28.484 MiB       ds = yt.load(prefix+'{:04d}'.format(i)+".vtk")
    48  213.121 MiB    0.125 MiB       dpar = (ds.index.grids[0])["dpar"].value[:, :, 0]
    49  213.621 MiB    0.500 MiB       tmp = np.fft.fft2(dpar)
    50  213.621 MiB    0.000 MiB       amp[i] = np.sum(abs(tmp[nwave::ds.domain_dimensions[0]-nwave*2, 0])) / abs(tmp[0][0])
    51  213.621 MiB    0.000 MiB       t[i] = ds.current_time
    52
    53  213.621 MiB    0.000 MiB       i = 3
➜➜  54  242.070 MiB   28.449 MiB       ds = yt.load(prefix+'{:04d}'.format(i)+".vtk")
    55  242.074 MiB    0.004 MiB       dpar = (ds.index.grids[0])["particle_density"].value[:, :, 0]
    56  242.574 MiB    0.500 MiB       tmp = np.fft.fft2(dpar)
    57  242.574 MiB    0.000 MiB       amp[i] = np.sum(abs(tmp[nwave::ds.domain_dimensions[0]-nwave*2, 0])) / abs(tmp[0][0])
    58  242.574 MiB    0.000 MiB       t[i] = ds.current_time
    59
    60  242.582 MiB    0.008 MiB       print(t[:i+1], amp[:i+1])
```

I don't quite understand this behavior. Encapsulating `yt.load()` and FFT analyses into a function does not help at all.
I've seen better results from my friend with hdf5 files where `yt.load()` does not become a memory hog and `all_data()` method consumes memory (but also release garbage).
![wechatimg321](https://user-images.githubusercontent.com/3999966/39658268-770e0020-4fc6-11e8-83f7-f151464918cc.jpeg)

**Comment by ngoldbaum** [comment] 2018-05-05 01:16
Ah, sorry, John’s right, ignore my comment.

**Comment by ngoldbaum** [comment] 2018-05-05 01:17
For the memory issue, can you share the code you’re running? Is it structured in such a way that the dataset object can get garbage collected?

**Comment by astroboylrx** [comment] 2018-05-05 01:43
@ngoldbaum @jzuhone  Sorry, I was initially trying to look into the memory issue but found something else...

I uploaded the data I used and my python script as well as my console output files at http://use.yt/upload/087b6f80 .

Do you mind playing with it? To benchmark memory, you may need to install [memory_profiler](https://pypi.org/project/memory_profiler/)

**Comment by astroboylrx** [comment] 2018-05-05 02:10
@jzuhone Maybe I didn't understand it correctly. From the link you mentioned
https://yt-project.org/doc/visualizing/manual_plotting.html?highlight=fixed%20resolution
It says "the FRB returns a fully pixelized image". I tried with this method. `frb['dpar']` can give me the right image, but frb["dpar"] does not give me the right values that match my data. I'm not sure if it is something to do with units.

 Since my goal is to perform FFT analyses, I need a way to get the data instead of plotting.

Here is the trial:
```bash
In [2]: ds = yt.load("comb/Parsg_Strat2d.0000.dpar.vtk")
   ...: c = ds.find_max('dpar')[1]
   ...: proj = ds.proj('dpar', 2)
   ...: width = (0.4, 'code_length')
   ...: res = [128, 64]
   ...: frb = proj.to_frb(width, res, center=c)
   ...:
   ...: print(ds.all_data()['dpar'].max(), frb['dpar'].max())
   ...:
   ...:
yt : [INFO     ] 2018-05-04 19:05:15,308 Temporarily setting domain_right_edge = -domain_left_edge. This will be corrected automatically if it is not the case.
/Users/rixin/projects/venvs/asf/lib/python3.6/site-packages/yt/frontends/athena/data_structures.py:521: RuntimeWarning: invalid value encountered in true_divide
  self.domain_dimensions = np.round(self.domain_width/grid['dds']).astype('int32')
yt : [WARNING  ] 2018-05-04 19:05:15,316 Assuming 1.0 = 1.0 cm
yt : [WARNING  ] 2018-05-04 19:05:15,318 Assuming 1.0 = 1.0 s
yt : [WARNING  ] 2018-05-04 19:05:15,318 Assuming 1.0 = 1.0 g
yt : [INFO     ] 2018-05-04 19:05:15,368 Parameters: current_time              = 0.0
yt : [INFO     ] 2018-05-04 19:05:15,368 Parameters: domain_dimensions         = [        128          64 -2147483648]
yt : [INFO     ] 2018-05-04 19:05:15,369 Parameters: domain_left_edge          = [-0.2 -0.1  0. ]
yt : [INFO     ] 2018-05-04 19:05:15,369 Parameters: domain_right_edge         = [ 0.2  0.1 -0. ]
yt : [INFO     ] 2018-05-04 19:05:15,393 Parameters: cosmological_simulation   = 0.0
yt : [INFO     ] 2018-05-04 19:05:15,799 Max Value is 4.01101e+01 at -0.0015625000000000 -0.0015625000000000 0.5000000000000000
yt : [INFO     ] 2018-05-04 19:05:15,807 Projection completed
yt : [INFO     ] 2018-05-04 19:05:15,809 Making a fixed resolution buffer of (dpar) 128 by 64
40.11006164550781 dimensionless 30.08254623413086 cm
```

**Comment by jzuhone** [comment] 2018-05-05 02:35
Hi @astroboylrx,

I should have been a bit more specific but I was typing from a phone at the time. Let me flesh this out a bit more.

So if you do `dd = ds.all_data()`, what you get is a yt "data object" containing all the data. Then you can get data from those arrays like you were doing, `dd["dpar"]`, etc. The reason these are 1D arrays is because yt was originally designed with 3D adaptive mesh data in mind, and so if you want to get _all_ the data on the different refinement levels it makes sense to return it as a 1D array since then you're not manipulating the data in any way by interpolating it to a uniform grid or something like that. 

However, of course your example is a 2D uniform grid, which is much simpler. Normally when people want uniform grid data we recommend using a [covering grid](http://yt-project.org/doc/cookbook/constructing_data_objects.html?highlight=covering%20grid#extracting-fixed-resolution-data) or a [fixed resolution buffer](https://yt-project.org/doc/visualizing/manual_plotting.html?highlight=fixed%20resolution), the latter I already mentioned. However, since your data is contained in one grid only, the solution you already identified is probably the best one:

```python
ds = yt.load("data.vtk")
ad = ds.index.grids[0]
print(ad["dpar"])
```
If you had more than one grid covering the entire dataset at uniform resolution then we'd probably have to recommend going the covering grid approach. I suspect that would look something like this:

```python
ds = yt.load("data.vtk")
level = 0
left_edge = ds.domain_left_edge
dims = ds.domain_dimensions
cg = ds.covering_grid(level, left_edge, dims)
print(cg["dpar"])
```
For your data these two approaches should give you the same answer, and the latter is more general. But since you only have one grid I think that you should go with the first option as it is simpler. 

If you want to get a better understanding of how yt thinks about data objects check out our documentation here:

http://yt-project.org/doc/analyzing/objects.html

I agree with @ngoldbaum that for the memory leak problem you should probably file a new issue, since that is definitely a problem we'll want to look into in more detail and we like to keep different issues separate on Github so they are easier to track.

**Comment by ngoldbaum** [comment] 2018-05-05 04:26
I just opened #1776 to track the memory usage of the unit system. It would still be great to get that full time series if you can share it, I'd love to reproduce the really excessive memory usage that originally triggered this report!

By the way, I like using [tracemalloc](https://docs.python.org/3/library/tracemalloc.html) and [objgraph](https://mg.pov.lt/objgraph) to debug python memory leaks. The former is great for identifying where really big chunks of memory are getting *allocated*. The latter is great for detecting objects that got created but not freed by an operation that shouldn't leak memory (e.g. a function call that should have no side effects). It also has facilities to generate nice graphs of object references and backreferences. It was using objgraph that I realized that the memory in your memory profiler run might be getting used by the caches in yt's unit system.

**Comment by astroboylrx** [comment] 2018-05-05 06:35
Hi, @jzuhone Thank you so much for the detailed explanations! Makes a lot of sense. 

@ngoldbaum I'm happy to share those files. Thank you for opening a new issue for me (sorry I went to cook dinner...). Let me continue in #1776

**Comment by ngoldbaum** [comment] 2018-05-05 19:32
I think the original question has been satisfactorily resolved. Let's close this issue.

**Closed by ngoldbaum** 2018-05-05 19:32 UTC
