### ISSUE TITLE
A bug in arepo test

### ISSUE THREAD

**Issue by vikramkhaire** [yt-project/yt#2242] opened 2019-04-16 12:51 UTC
### Bug report
I was trying some test examples as suggested in the yt/yt/frontends/arepo/tests. I downloaded the ArepoBullet data. And tried following

**Code for reproduction**
```
import yt
#file= path and file where the snapshot_150.hdf5 stored
ds=yt.load(file)
ds.print_stats()
```

**I get the following error message**

```
#
yt : [INFO     ] 2019-04-16 05:07:48,529 Allocating for 2.653e+07 particles
Initializing coarse index :   0%|                                                                                                                     | 0/51 [00:00<?, ?it/s]---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/yt/yt/geometry/particle_geometry_handler.py in _initialize_index(self)
    142         try:
--> 143             rflag = self.regions.load_bitmasks(fname)
    144             rflag = self.regions.check_bitmasks()

~/yt/yt/geometry/particle_oct_container.pyx in yt.geometry.particle_oct_container.ParticleBitmap.load_bitmasks()

OSError: 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-14-d2b97580ae55> in <module>()
----> 1 ds.print_stats()

~/yt/yt/utilities/parallel_tools/parallel_analysis_interface.py in root_only(*args, **kwargs)
    317     def root_only(*args, **kwargs):
    318         if not parallel_capable:
--> 319             return func(*args, **kwargs)
    320         comm = _get_comm(args)
    321         rv = None

~/yt/yt/data_objects/static_output.py in print_stats(self)
    552     @parallel_root_only
    553     def print_stats(self):
--> 554         self.index.print_stats()
    555 
    556     @property

~/yt/yt/data_objects/static_output.py in index(self)
    514                 raise RuntimeError("You should not instantiate Dataset.")
    515             self._instantiated_index = self._index_class(
--> 516                 self, dataset_type=self.dataset_type)
    517             # Now we do things that we need an instantiated index for
    518             # ...first off, we create our field_info now.

~/yt/yt/geometry/particle_geometry_handler.py in __init__(self, ds, dataset_type)
     41         self.float_type = np.float64
     42         super(ParticleIndex, self).__init__(ds, dataset_type)
---> 43         self._initialize_index()
     44 
     45     def _setup_geometry(self):

~/yt/yt/frontends/sph/data_structures.py in _initialize_index(self)
     90             self.io._generate_smoothing_length(self.data_files, self.kdtree)
     91 
---> 92         super(SPHParticleIndex, self)._initialize_index()
     93 
     94     def _generate_kdtree(self, fname):

~/yt/yt/geometry/particle_geometry_handler.py in _initialize_index(self)
    148         except OSError:
    149             self.regions.reset_bitmasks()
--> 150             self._initialize_coarse_index()
    151             self._initialize_refined_index()
    152             wdir = os.path.dirname(fname)

~/yt/yt/geometry/particle_geometry_handler.py in _initialize_coarse_index(self)
    172                     hsml = None
    173                 self.regions._coarse_index_data_file(
--> 174                     pos, hsml, data_file.file_id)
    175             self.regions._set_coarse_index_data_file(data_file.file_id)
    176         pb.finish()

~/yt/yt/geometry/particle_oct_container.pyx in yt.geometry.particle_oct_container.ParticleBitmap._coarse_index_data_file()

ValueError: Buffer dtype mismatch, expected 'float' but got 'double'


<!--The output produced by the above code, which may be a screenshot, console
output, etc.-->

```

**Note**
I get the same error even if I use:
```
from yt.frontends.arepo.api import ArepoHDF5Dataset as arepo
ds=arepo(file)
ds.print_stats()
```

**Version Information**
  * Operating System: Ubuntu
  * Python Version: 3.6
  * yt version: 4.0

**Comment by jzuhone** [comment] 2019-04-16 12:56
@vikramkhaire have you updated to the current tip of the yt-4.0 branch? This bug is already fixed there.

**Comment by vikramkhaire** [comment] 2019-04-16 13:05
How to use the 'current tip' and update? I did pull and develop/install.

**Comment by ngoldbaum** [comment] 2019-04-16 13:07
What's the output of `git rev-parse HEAD`?

**Comment by vikramkhaire** [comment] 2019-04-16 13:15
e1848447c55fa10d08f7068e5ca0d53fd4c6409f

**Comment by ngoldbaum** [comment] 2019-04-16 13:17
OK, that is the current tip. I'll try to reproduce this later but @jzuhone may be able to help in the meantime. The reason he says that this is already fixed is because he put in PR #2236 the other day, but perhaps we have another place where smoothing lengths or positions should be cast to float64...

**Comment by vikramkhaire** [comment] 2019-04-16 13:19
Looks like that. Thanks @ngoldbaum and @jzuhone

**Comment by vikramkhaire** [comment] 2019-04-16 22:35
I think the issue might be the test simulation itself. The same code does not give similar error on a few of the illustris simulations. There is another issue  as noted in #2243

**Comment by ngoldbaum** [comment] 2019-04-17 15:03
Thank you for the report! Now that #2244 has been merged this should be fixed.

**Closed by ngoldbaum** 2019-04-17 15:03 UTC
Labels: triage
