### ISSUE TITLE
Missing/wrong(?) Enzo AMR data

### ISSUE THREAD

**Issue by pgrete** [yt-project/yt#1427] opened 2017-05-26 19:36 UTC
### Bug report

**Bug summary**
Enzo AMR data is potentially read or initialized incorrectly (or sth is wrong with the data itself)
**Code for reproduction**

Notebook: https://gist.github.com/pgrete/dc0b485f0bd3448d1c14cb4141a0ed9b
Data: http://use.yt/upload/6656ee5a

**Version Information**

  * Operating System: SUSE Linux Enterprise Server 11 (x86_64)
  * Python Version: 3.6.1
  * yt version: 3.4-dev c18a76a7f5369

dependencies with conda, yt from source

**Comment by ngoldbaum** [comment] 2017-05-26 19:55
As far as I can see this is happening inside the pixelizer itself. Here's a test script that makes what's happening a little bit more obvious:

```
import yt

ds = yt.load("DD0025/data0025")

plot = yt.SlicePlot(ds, 'z', 'density',
                    width=(0.003, 'pc'),
                    center='m',
                    origin='native')

plot.set_axes_unit('code_length')

plot.annotate_grids(draw_ids=True)

plot.save()
```

When I print the data in grid 949 (the one with the missing values in the SlicePlot) I do not see any bad data. I also do not see any bad data when I add a breakpoint right before the pixelizer is called and look at the field values returned by the slice data object.

Perhaps some sort of floating point round-off mistake in the pixelizer?

**Comment by ngoldbaum** [comment] 2017-05-26 20:11
It might be worth mentioning that grid 949 is at AMR level 25 and the maximum AMR level in this dataset is 40.

**Comment by ngoldbaum** [comment] 2017-05-26 20:42
I inserted a breakpoint right before the pixelizer gets called in `cartesian_coordinates.py`. After running my script from two comments ago, I see the following:

```
(Pdb) ret = ((data_source['px'] - data_source['pdx'] < bounds[1]) & (data_source['px'] + data_source['pdx'] > bounds[0]) & (data_source['py'] - data_source['pdy'] < bounds[3]) & (data_source['py'] + data_source['pdy'] > bounds[2]))
(Pdb) np.where(ret)[0].shape
(36,)
```

The first line is doing the exact same checks that `pixelize_cartesian` does to figure out whether a given zone in the simulation contributes to an image. So it seems that only 36 zones contribute, which agress with what I see in the final image. So I guess the problem is that somehow the auxililary `px`, `py`, `pdx`, and `pdy` fields are somehow incorrect? I don't think the pixelizer is buggy anyway, it's doing the correct thing given the data being fed in.

**Comment by ngoldbaum** [comment] 2017-05-26 21:25
If I append the following to my script, I get:

```
g = ds.index.grids[948]
fcoords = g.select_fcoords(plot.data_source)
print(fcoords.shape[0])
print(g.ActiveDimensions[0] * g.ActiveDimensions[1])
```

I get:

```
720
792
```

The difference is 72, which is exactly the number of zones missing from the final SlicePlot, if I count by eye.

So I guess the issue is in the selector?

**Comment by ngoldbaum** [comment] 2017-05-26 21:37
Ah, and it's because this grid isn't a leaf grid. The blank spot is supposed to be getting filled in by child grids but for some reason that's not happening.

**Comment by ngoldbaum** [comment] 2017-05-26 22:04
So I think I understand what's happening, at least for the slices:

```
In [1]: g = ds.index.grids[949]

In [2]: g.LeftEdge
Out[2]: YTArray([ 0.49150733,  0.50526053,  0.49058056]) code_length

In [3]: g.LeftEdge[2]
Out[3]: 0.49058055575006 code_length

In [4]: plot.data_source.coord
Out[4]: 0.4905805557500548 code_length
```

Grid 950 is *supposed* to be filling in these data, but its left_edge is epsilon away from the slice coordinate, so it's skipped.

**Comment by ngoldbaum** [comment] 2017-05-26 22:15
Yup, if I choose an ever so slightly different slice coordinate, (`0.490580555750061` instead of `0.4905805557500548`) I get a sane looking plot:

![data0025_slice_z_density](https://cloud.githubusercontent.com/assets/3126246/26514363/fb23bf7e-4236-11e7-828b-77cd6281a290.png)

**Comment by ngoldbaum** [comment] 2017-05-29 18:56
This is really two issues, one to do with slicing, another to do with projections. I've opened two new issues to track these problems. I'm going to go ahead and close this one, let's move discussion to those issues.

**Closed by ngoldbaum** 2017-05-29 18:56 UTC
