### ISSUE TITLE
Problems with the particle_trajectories documentation/module (1/2)

### ISSUE THREAD

**Issue by mtryan83** [yt-project/yt#4765] opened 2023-12-21 03:21 UTC
### Bug report

**Bug summary**

Running the example code for the [particle_trajectories](https://yt-project.org/doc/reference/api/yt.data_objects.particle_trajectories.html#yt.data_objects.particle_trajectories.ParticleTrajectories) module fails with the error `RuntimeError: yt attempted to read outside the boundaries of a non-periodic domain along dimension 0.`

**Code for reproduction**

```python
import yt
import glob
my_fns = glob.glob("orbit_hdf5_chk_00[0-9][0-9]")
my_fns.sort()
fields = [ ("all", "particle_position_x") ] # simplified for brevity
ds = load(my_fns[0])
init_sphere = ds.sphere(ds.domain_center, (0.5, "unitary"))
indices = init_sphere[("all", "particle_index")].astype("int64")
ts = DatasetSeries(my_fns)
trajs = ts.particle_trajectories(indices, fields=fields)
```
(shorter, equivalent version):
```python
import yt
fields = [ ("all", "particle_position_x"),] # simplified for brevity
ts = yt.load("orbit_hdf5_chk_000?")
ds = ts[0]
init_sphere = ds.sphere(ds.domain_center, (0.5, "unitary"))
indices = init_sphere[("all", "particle_index")].astype("int64")
trajs = ts.particle_trajectories(indices, fields=fields, suppress_logging=True)
```

**Actual outcome**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.conda/envs/test_yt/lib/python3.11/site-packages/yt/data_objects/time_series.py", line 434, in particle_trajectories
    return ParticleTrajectories(
           ^^^^^^^^^^^^^^^^^^^^^
  File "~/.conda/envs/test_yt/lib/python3.11/site-packages/yt/data_objects/particle_trajectories.py", line 147, in __init__
    self._get_data(fields)
  File "~/.conda/envs/test_yt/lib/python3.11/site-packages/yt/data_objects/particle_trajectories.py", line 278, in _get_data
    cube = grid.retrieve_ghost_zones(1, grid_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.conda/envs/test_yt/lib/python3.11/site-packages/yt/data_objects/index_subobjects/grid_patch.py", line 265, in retrieve_ghost_zones
    cube = self.ds.covering_grid(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.conda/envs/test_yt/lib/python3.11/site-packages/yt/data_objects/construction_data_containers.py", line 723, in __init__
    self.get_data(fields)
  File "~/.conda/envs/test_yt/lib/python3.11/site-packages/yt/data_objects/construction_data_containers.py", line 910, in get_data
    self[a] = self._data_source[f]
              ~~~~~~~~~~~~~~~~~^^^
  File "~/.conda/envs/test_yt/lib/python3.11/site-packages/yt/data_objects/data_containers.py", line 235, in __getitem__
    self.get_data(f)
  File "~/.conda/envs/test_yt/lib/python3.11/site-packages/yt/data_objects/selection_objects/data_selection_objects.py", line 140, in get_data
    self.index._identify_base_chunk(self)
  File "~/.conda/envs/test_yt/lib/python3.11/site-packages/yt/geometry/grid_geometry_handler.py", line 333, in _identify_base_chunk
    gi = dobj.selector.select_grids(
         ^^^^^^^^^^^^^
  File "~/.conda/envs/test_yt/lib/python3.11/site-packages/yt/data_objects/selection_objects/data_selection_objects.py", line 90, in selector
    self._selector = sclass(self)
                     ^^^^^^^^^^^^
  File "yt/geometry/_selection_routines/region_selector.pxi", line 60, in yt.geometry.selection_routines.RegionSelector.__init__

RuntimeError: yt attempted to read outside the boundaries of a non-periodic domain along dimension 0.
Region left edge = -0.0625 code_length, Region right edge = 0.5625 code_length
Dataset left edge = 0.0 code_length, Dataset right edge = 1.0 code_length

This commonly happens when trying to compute ghost cells up to the domain boundary. Two possible solutions are to select a smaller region that does not border domain edge (see https://yt-project.org/docs/analyzing/objects.html?highlight=region)
or override the periodicity with
ds.force_periodicity()

```

**Expected outcome**

A ParticleTrajectories object, `traj`.

**Version Information**

  * Operating System: Fedora 38
  * Python Version: 3.11
  * yt version: 4.2.1, 4.3
  * Other Libraries (if applicable):

yt is installed through the conda-forge channel.

**Additional Comments**
Briefly, it looks like the problem occurs when `yt` tries to add `("all","particle_position_x")` as a grid field in the `_get_data()` function. I don't know if that's expected or not. Note that `("io","particle_position_x")` works just fine, presumably because it's not a grid field (i.e. passes the `if ftype in self.data_series[0].particle_types:` statement in line 237). I don't know the FLASH format, so I don't know if "all" and "io" are equivalent. Alternatively, it might be a problem in how the grid is loaded?

Also, I'd expect the test `test_particle_trajectories.py::test_orbit_traj` to fail based on this, but wasn't able to test.

**Comment by neutrinoceros** [comment] 2023-12-21 12:05
duplicate of https://github.com/yt-project/yt/issues/4590

**Closed by neutrinoceros** 2023-12-21 12:05 UTC

**Comment by neutrinoceros** [comment] 2023-12-21 12:07
@mtryan83 Your report has valuable insight that should be added to the original issue, can you do that please ?

**Comment by mtryan83** [comment] 2023-12-21 19:48
Yeah, that's my bad, I completely forgot to check for previous issues. I'll do that.
