### ISSUE TITLE
adding a point source to VR makes volumesource vanish

### ISSUE THREAD

**Issue by zingale** [yt-project/yt#2614] opened 2020-05-30 23:52 UTC
If you make a VR with a VolumeSource and add a PointSource, sometimes you will no longer see the VolumeSource.  Sometimes you can fix this by using sigma_clip values of 1000 or more, but there should be another way.

### Bug report

**Bug summary**

**Code for reproduction**

```python
import numpy as np
import yt
from yt.visualization.volume_rendering.api import Scene, VolumeSource, PointSource
from yt.units import kpc

ds = yt.load("IsolatedGalaxy/galaxy0030/galaxy0030")

# create a scene and add volume sources to it

sc = Scene()

# Add density

field = "density"
ds._get_field_info(field).take_log = True

vol = VolumeSource(ds, field=field)
vol.use_ghost_zones = True

tf =  yt.ColorTransferFunction([-27, -25])
tf.clear()
tf.add_layers(4, 0.02, alpha=np.logspace(-3, -1, 4), colormap="winter")

vol.set_transfer_function(tf)
sc.add_source(vol)

# add a point source

pt = 1.1*ds.domain_center

vertices = np.zeros((1, 3))
colors = np.zeros((1, 4))
colors[0, :] = (0.2, 0.2, 0.2, 0.1)

radii = np.zeros((1), dtype=np.int64)

radii[0] = 5

vertices[0,:] = pt

points = PointSource(vertices, radii=radii, colors=colors)
sc.add_source(points)




# setup the camera

cam = sc.add_camera(ds, lens_type="perspective")
cam.resolution = (1200, 800)
cam.zoom(20.0)

# Render the image.

sc.render()

sc.save_annotated("render_test.png", sigma_clip=1.)

```

**Actual outcome**

you only see the point in this image.  If you comment out the PointSource line, then you will see the Galaxy VR just fine.

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

We should be able to see both sources at once.

**Version Information**

  * Operating System: Fedora 32
  * Python Version: 3.7.7
  * yt version: 3.7dev0
  * Other Libraries (if applicable):

**Comment by neutrinoceros** [comment] 2021-10-21 18:11
Unfortunately this has become irreproducible now that `VolumeSource` was removed from the api module and made an abstract class.
I'll close this but feel free to reopen @zingale, I don't recall the reasons why the changes I mentioned were performed and it's possible they were unsufficiently justified.

**Closed by neutrinoceros** 2021-10-21 18:11 UTC
Labels: triage
