### ISSUE TITLE
matplotlib 3.4.3 returns get_data_path as PosixPath

### ISSUE THREAD

**Issue by zingale** [yt-project/yt#3479] opened 2021-08-24 16:34 UTC
### Bug report

When using the latest yt (on `main` in git) and MPL 3.4.3, I get a traceback:

```
Traceback (most recent call last):
  File "/raid/zingale/development/Castro/Exec/science/massive_star/massive_star_slice.py", line 48, in <module>
    sp = yt.SlicePlot(ds, "theta", f,
  File "/raid/zingale/development/yt-mz/yt/yt/visualization/plot_window.py", line 2484, in SlicePlot
    return AxisAlignedSlicePlot(ds, normal, fields, *args, **kwargs)
  File "/raid/zingale/development/yt-mz/yt/yt/visualization/plot_window.py", line 1614, in __init__
    PWViewerMPL.__init__(
  File "/raid/zingale/development/yt-mz/yt/yt/visualization/plot_window.py", line 872, in __init__
    PlotWindow.__init__(self, *args, **kwargs)
  File "/raid/zingale/development/yt-mz/yt/yt/visualization/plot_window.py", line 221, in __init__
    super().__init__(data_source, window_size, fontsize)
  File "/raid/zingale/development/yt-mz/yt/yt/visualization/plot_container.py", line 912, in __init__
    super().__init__(data_source, figure_size, fontsize)
  File "/raid/zingale/development/yt-mz/yt/yt/visualization/plot_container.py", line 260, in __init__
    font_path = matplotlib.get_data_path() + "/fonts/ttf/STIXGeneral.ttf"
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
```

The issue is that MPL returns a PosixPath object now:

```
In [4]: matplotlib.get_data_path()                                                                                                                                               
Out[4]: PosixPath('/usr/share/matplotlib/mpl-data')
```

Note that MPL 3.4.1 seems to return a string, so this is a very recent change.

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Version Information**

  * Operating System:
  * Python Version:
  * yt version:
  * Other Libraries (if applicable):

**Comment by zingale** [comment] 2021-08-24 16:35
we can probably just do a `try` / `except` block here.  I'll try to PR a fix shortly.

**Comment by neutrinoceros** [comment] 2021-08-25 10:12
I can't reproduce this on my system. The function still returns a string on matplotlib 3.4.3 and even on their master branch.

The source code for this function still seems like it's clearly _meant_ to return a string.
```
@_logged_cached('matplotlib data path: %s')
def get_data_path():
    """Return the path to Matplotlib data."""
    return str(Path(__file__).with_name("mpl-data"))
```

So I think we need to report this as a bug upstream.
@zingale, could you report this upstream, or would you give me a hand with the discussion ? I can fill in a report but I'll be stuck as soon as matplotlib maintainers ask me how to reproduce it :)

**Comment by zingale** [comment] 2021-08-25 12:14
done.  Issue: https://github.com/matplotlib/matplotlib/issues/20900

**Comment by neutrinoceros** [comment] 2021-08-25 12:22
excellent, thank you !
I think we can close this one now.

**Closed by neutrinoceros** 2021-08-25 12:22 UTC

**Comment by zingale** [comment] 2021-08-25 12:31
this might be a packaging issue.  The MPL 3.4.3 from Fedora does this but the same version from pip does not.  I'll just use pip as a workaround.

**Comment by neutrinoceros** [comment] 2021-08-25 12:56
weird. Can't wait to see how this unravels !
