### ISSUE TITLE
ENH: Summary Statistics shortcut

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt#4202] opened 2022-11-08 20:37 UTC
Computing the min, max, variance and mean of a field should be accessible through a single call, much [like it is in pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html).  In pandas, numerical columns output:

 - count
 - mean
 - std
 - min
 - max

Since most of these can be computed in a single pass, it would be useful to do the same in yt.  As an example, right now this would require calling `.mean()`, `.max()`, `.min()`, and `.std()` on a data object; min and max are both calculated in the same pass so this would be reusable, but we could batch the whole thing.

**Comment by neutrinoceros** [comment] 2022-12-07 18:02
isn't this a dupe of https://github.com/yt-project/yt/issues/2737 ?

**Comment by matthewturk** [comment] 2022-12-07 18:47
...yes

**Comment by neutrinoceros** [comment] 2022-12-08 08:55
I'll move the additional insight over there

**Closed by neutrinoceros** 2022-12-08 08:55 UTC
Labels: enhancement
